### ISSUE TITLE
Figure out why default values in InputPort descriptors are ignored.

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#1252]
The behavior tree library allows one to specify default values to InputPorts, however, that value seems to be ignored when I tested with the RateController object.

If we can get default values working, we can remove the checks on input values in the "NavigateToPose" node.

_Originally posted by @crdelsey in https://github.com/ros-planning/navigation2/pull/1251/review_comment/create_

**Comment by SteveMacenski** [comment]
That was also true before in v2. I ran into that fun fact when testing the backup parameterization

**Comment by shivaang12** [comment]
@SteveMacenski Can you provide me some more context for this problem? Thanks!

**Comment by SteveMacenski** [comment]
Essentially, these defaults (https://github.com/ros-planning/navigation2/blob/master/nav2_behavior_tree/plugins/action/spin_action.cpp#L49) are not being properly used. The "InputPorts" are the inputs that can be taken by a behavior tree node, and there are a number of them. What we have done to get around this is require all XML nodes to fully fill out the inputs or in the setup of the BT node, we try to get it with some bogus number (like duration = -1) and if its still that bogus number on the output, we set to some logical default because clearly it wasnt set (when it was supposed to be) from `getInput` (https://github.com/ros-planning/navigation2/blob/master/nav2_behavior_tree/plugins/action/spin_action.cpp#L41)

**Comment by shivaang12** [comment]
Okay on it!

**Comment by shivaang12** [comment]
I have opened an issue about this in BehaviorTree.CPP repo here BehaviorTree/BehaviorTree.CPP#153

**Comment by SteveMacenski** [comment]
Fixed in BehaviorTree/BehaviorTree.CPP#153
