### ISSUE TITLE
Replan immediately on plan invalidation

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#1395]
Right now we only replan on the 1hz cycle.

Imagine you have a robot moving at 4 m/s. Within 1 second a new plan out be computed 4 meters later. If someone is 6 meters away when that happens, the replan will be extremely evasive and not appear to be going around the person until the last moment. If any closer, then the local planner would fail to compute a plan and immediately stop from 4m/s abruptly, and also be extremely threatening or dangerous.

Imagine also a situation where you only replan once every 30s because you don't want to have oscillatory behavior in the case of many valid and similar paths down different forks.

---

So the feature - we need to be able to replan immediate after a plan is invalidated as well as replan immediately after the controller fails to compute a plan as the first recovery in case that is also just from something in the way. If that new plan also fails to be able to compute a control effort, then clear costmaps and other options (or maybe clear costmaps then replan? Or just at the same time).

**Comment by mkhansen-intel** [comment]
As I commented in #1387. I think this is solvable.
1. the looping rate can already be adjusted easily via the behavior tree XML (that's why we put it there)
2. If that is insufficient, we can push the looping logic down into the planner_server
3. We can add ability to request a new plan via to the controller_server if needed
4. We can retry planning before trying recoveries

Let's talk in the Nav2 WG.
