### ISSUE TITLE
New feature with test policy

### ISSUE THREAD

**Issue by shivaang12** [ros-planning/navigation2#1667]
I am suggesting to have compulsory test (at least unit test) included with the new feature which I think would be helpful to keep the coverage in check. I think this is one of the things which `MOVEIT` follows and is working very well for them.

I am suggesting a PR policy for new feature for Navigation2 that from now on each feature there should be at least unit test which would validate the implementation.

Putting this on floor for discussion.

**Comment by SteveMacenski** [comment]
@shivaang12 I'm going to close this only because once the dependency stack gets quality levels, we will be required to provide exactly this as part of the quality level discussion. Since there's another impending trigger for it, the ticket here is largely redundant. 

Though if you're interested in proposing a policy, then I'm open to hearing it and we can integrate sooner than later in that case. For the moment,  I don't want to be doing redundant efforts.
