### ISSUE TITLE
Create a module for mapping from BT to Action

### ISSUE THREAD

**Issue by ymd-stella** [ros-planning/navigation2#1979]
## Feature request

Related to https://github.com/ros-planning/navigation2/pull/1928#issuecomment-685995092

#### Feature description

- A generic application server that people can use to build their specific autonomy applications.
  - It loads and executes BT and provides an interface as an action server.
  - This makes it easy to provide an action with a user-defined BT.
- A module for mapping from BT to Action (like BtActionNode mapping from Action to `BT::ActionNodeBase`)
- It is similar to BtNavigator, but it applies to general actions.

##### plan A: template

- class name: BtApplicationServer
- Inherit: `nav2_util::LifecycleNode`
- Template arg: Action type (`ActionT`)
- Key functions:
  - Create action server (`nav2_util::SimpleActionServer<ActionT>`)
  - Load BT from file specified by goal
  - Provide the interfaces below
    - `on_initialize_blackboard`: Initialize blackboard (ex. Set goals)
    - `on_bt_loop`; Publish feedback by action server
    - `on_bt_shutdown`: Return result by action server
- Constraints:
  - `ActionT::Goal` must have `string bt_xml_filename`

##### plan B: generic action

- Inherit: `nav2_util::LifecycleNode`
- Key functions:
  - Create action server (`nav2_util::SimpleActionServer<PerformTask>`)
  - Load BT from file specified by goal
  - Provide generic feedback and result.
- Constraints:
  - `PerformTask::Goal` must have `string bt_xml_filename`
  - `PerformTask::Goal` must have something like `Something[] ports`

##### plan A vs. plan B
- plan A
  - The user implements a BT, and extend `BtApplicationServer<ActionT>` to create their own application classes and implement some methods.
  - Custom feedbacks and results can be handled.
- plan B
  - The user implements a BT only.

**Comment by SteveMacenski** [comment]
Apologies, I don't understand the context / what your goal is here. The navigation to pose action can field a behavior tree in its request to use, so is that not already a BT to action call map?

I'm thinking your referencing our discussion on some kind of generic application server that people can use to build their specific autonomy applications, from your link and the implementation considerations, but I suppose the "feature description" section is a little less clear to me.

@mikeferguson do you have thoughts on this version of it? I don't have a strong vision for how this might turn out. Ideally, I think the best situation would be to create a server with a sufficiently generic action message definition that can be used for creating autonomy applications taking in a BT path, which I describe in that PR. This way its all about the BT and the action message population and a user doesn't have to implement and potentially fork the codebase to create a new server with their custom action template.

I think the template thing for the BT nodes works because the BTs are small runtime setable plugins, so a BT designer doesn't need to fork navigation2 to add a new BT plugin, they just need to build their own package of them and add to BT and it should work. This I think would require someone to modify this codebase since the template would be part of the server, not a smaller plugin component of it (but might be possible to make it that way?).

**Comment by SteveMacenski** [comment]
Thanks for the update. Have you done any thinking on them as to which could be more implementable / what the `Something` message might be?

**Comment by ymd-stella** [comment]
> which could be more implementable

Plan A is easier to implement because there are fewer unknowns in the implementation.

> what the Something message might be?

My idea was to define Something as a string-key-value-pair.
It is assumed to be set in blackboard as a string value and converted to the proper type by convertFromString when it is read.
My concern is that I don't know whether or not convertFromString is called when reading from Blackboard to BT xml.

**Comment by ymd-stella** [comment]
@SteveMacenski  Can I get your feedback?
