### ISSUE TITLE
Reconfigurable parameter tuning GUI

### ISSUE THREAD

**Issue by doisyg** [ros-planning/navigation2#2160]
Hi,
New to ros2 and navigation2. I am trying to tune the multiple navigation parameters. In ROS1 I was using the `rqt_reconfigure` tool, what are you guys using for nav2 ? There is a port of `rqt_reconfigure` but is seems completely unusable with foxy (at least on my system). https://github.com/ros-visualization/rqt_reconfigure/tree/dashing

(Can move to answers.ros.org if needed)

**Comment by SteveMacenski** [comment]
There is no GUI, but a ticket open to re-enable runtime reconfigurable parameterizations https://github.com/ros-planning/navigation2/issues/956. I think DWB is the only one with largely complete reconfigurability we were using as a POC before moving onto other topics. Dynamic reconfigure is dead in ROS 2 so I'm not sure what `rqt_reconfigure` would be / do in ROS 2.

**Comment by SteveMacenski** [comment]
But step 1 would be just "get runtime reconfigurable parameters even available", before that point, a GUI is pretty useless :laughing:

**Comment by doisyg** [comment]
Thanks for the clarification!
I would look into the reconfigurability of the parts I am intending to spend the most time tuning (TEB controller and Navfn planner). I see Costmap2D https://github.com/ros-planning/navigation2/pull/1370 seems already reconfigurable (at least each layer can be enable/disable), so that's a relief ^^

**Comment by SteveMacenski** [comment]
I'm pretty sure we removed costmap's at some point, I'd check the actual code.

... NavFn has like 2 parameters :-) TEB isn't in this project directly so not an opinion there. 

Can this be closed? Doesn't seem actionable

**Comment by sutharsan-311** [comment]
I ran into this issue while using Nav2 on UV disinfection robots in hospitals. Restarting everything just to change `inflation_radius` or MPPI weights was killing iteration time.

So I built a tool: **nav2_config**. It's a PyQt6 app that connects to a running Nav2 stack and lets you change parameters via `ros2 param set`, without restarting nodes.

What it does:
- Supports 278 parameters with descriptions and ranges, plus auto-discovers anything outside the schema (works with any plugin)
- Per-param Set button with status feedback (idle → ready → pending → success/fail)
- Automatic post-set service calls — costmap clear, AMCL nomotion update, map reload
- Goes through `lifecycle_manager` for lifecycle ops, not direct node transitions
- Loads/saves `nav2_params.yaml`

Repo: https://github.com/sutharsan-311/nav2_config

Tested on Humble. Should work on Iron and Jazzy since the APIs are the same, but haven't verified.

**Comment by SteveMacenski** [comment]
Isnt that very similar to rqt reconfigure?

**Comment by sutharsan-311** [comment]
similar idea, but different in how it actually works.

 `rqt_reconfigure` is a generic param editor, it shows raw parameter names with no descriptions, no ranges, and no idea what the params actually do. It also has no Nav2 specific awareness.

`nav2_config` is Nav2 specific:

- 278 parameters with descriptions and tuning guidance (not just raw names)
- Knows which params need post set actions like clears costmaps after `inflation_radius` changes, triggers AMCL `nomotion_update`, reloads map for `map_server`
- Handles Nav2's dot notation plugin namespacing (`FollowPath.max_vel_x`, `inflation_layer.inflation_radius`) which rqt_reconfigure doesn't understand cleanly
- Lifecycle management through `lifecycle_manager`  rqt_reconfigure has no lifecycle awareness at all
- Loads/saves `nav2_params.yaml` as the source of truth

Basically rqt_reconfigure is a screwdriver, nav2_config is a Nav2 specific tuning workbench.
