### ISSUE TITLE
'tb3_simulation_launch.py' was not found in the share directory

### ISSUE THREAD

**Issue by pablogs9** [ros-planning/navigation2#2195]
## Bug report

I have a ROS 2 Eloquent installation working and I have followed the steps in the [getting started tutorial](https://navigation.ros.org/getting_started/index.html). It seems to be not founding some files:

I have this error:

```bash
➜  ~ ros2 launch nav2_bringup tb3_simulation_launch.py

file 'tb3_simulation_launch.py' was not found in the share directory of package 'nav2_bringup' which is at '/opt/ros/eloquent/share/nav2_bringup'
```

**Required Info:**

- Operating System:
  -  Ubuntu 18.04
- ROS2 Version:
  -  Eloquent
- Version or commit hash:
  - 
- DDS implementation:
  -  FastRTPS

**Comment by SteveMacenski** [comment]
The instructions are for the latest distribution and master branches - we do not support Eloquent anymore. Eloquent is EOL and will recieve no support in this project or from ROS2 in general. 

https://github.com/ros-planning/navigation2/tree/eloquent-devel/nav2_bringup/bringup/launch but you can easily look through the source code and see it was just renamed 

Closing because we offer no support for Eloquent.
