### ISSUE TITLE
How can a behavior action node  communicate with the ros network?

### ISSUE THREAD

**Issue by pabloinigoblasco** [ros-planning/navigation2#2221]
Hello. 

I want to create a behavior action node that is able to read information from the ros network (via topic, or service). To do that I need a reference to a rclcpp::Node. 

What is the approach to follow here?
First question:
Does this concept match the design of navigation2 for the main developers of the stack?

If it does:
Should I get a reference of the bt_navigator rclcpp::Node from the behavior?
Should I create a rclcpp::Node internally to the behavior even if the lifecycle of the behavior is limited?

Is there any implemented behavior example that fits this idea?

I did it in this way (that probably is incorrect or could be something better) and works:
https://github.com/pabloinigoblasco/navigation2/commit/889796145aca9da9dbe6291a54dfa2285779aee5

**Comment by SteveMacenski** [comment]
I'd suggest looking at existing BT nodes in Nav2, which has access to rclcpp::Node's via the blackboard. But as a system designer, its up to you about the types of things you need to be doing and what processing model with nodes makes sense for your application. Typically though, the single blackboard node is going to be sufficient (unless you're adding in a bunch of extra subscribers / exposing services / etc) for publishers / clients since each node is processed in a single threaded manner.
