### ISSUE TITLE
Nav2 plans path through walls after clear global costmap

### ISSUE THREAD

**Issue by charlielito** [ros-planning/navigation2#2452]
## Bug report

- Operating System:
  - Docker + Ubuntu 20.04, 10th gen i7
- ROS2 Version:
  - Foxy binaries
- Version or commit hash:
  - Foxy
- DDS implementation:
  - cyclone 

#### Steps to reproduce issue
I am facing this same issue https://github.com/ros-planning/navigation2/issues/1999 where I see it was fixed with https://github.com/ros-planning/navigation2/pull/2090
Nonetheless I think this was not ported to foxy branch. 

#### Expected behavior
Don't plan through walls.

#### Actual behavior
Sometimes it plans through walls.

Would it be possible to introduce it to foxy? Do you think the fix here https://github.com/ros-planning/navigation2/pull/2090 will be compatible with foxy so a PR could be made?

**Comment by SteveMacenski** [comment]
You pointed towards the same things I was going to link you to, the discussion there is pretty clear for Foxy this is a wont fix. The patch is not ABI compatible with Foxy and you should move to Galactic or newer if you wish to use the patch. Else, you can attempt to migrate it yourself into a local fork but we cannot merge that solution into Foxy because it significantly breaks ABI policies. If you have a solution that wouldn't do that, I'm all ears and happy to merge.

**Comment by charlielito** [comment]
Ok, since this is a wont fix for foxy I'll close this. Thanks for the fast response
