### ISSUE TITLE
Move costmap / footprint subscribers and collision checking objects into nav2_util from costmap_2d

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2535]
costmap_subscriber.hpp 
 costmap_topic_collision_checker.hpp 
 footprint_collision_checker.hpp 
 footprint_subscriber.hpp 

All should be utils to be generally used since now being used in smoothers / recovery / assisted teleop. It is now more generally used and should be abstracted out for more clarity they exist. They seem to be being forgotten.

**Comment by MOLOCH-dev** [comment]
Do these need to work with template for NodeTypes or just work with Lifecycle Nodes?

**Comment by SteveMacenski** [comment]
That would be most ideal, but a direct port over would be sufficient to meet the needs of this ticket. But making a templated node type would be a great and easy addition!

**Comment by lucabonamini** [comment]
`costmap_subscriber.hpp`, `costmap_topic_collision_checker.hpp`, `footprint_collision_checker.hpp` depend on `nav2_costmap_2d /costmap_2d.hpp`, while `footprint_subscriber.hpp` depends on `nav2_costmap_2d/footprint.hpp`. But `nav2_util` cannot have `nav2_costmap_2d` as dependency, since `nav2_costmap_2d` already depends on `nav2_util`.

**Comment by SteveMacenski** [comment]
Thank you for the concise explanation, that totally makes sense. We cannot do this due to circular dependencies, so closing this out.

Thanks for your investigation on this!
