### ISSUE TITLE
Regular Pure Pursuit : Allow Reversing feature

### ISSUE THREAD

**Issue by kamakshijain** [ros-planning/navigation2#2551]
Hi
I believe based on my question here
https://answers.ros.org/question/375436/smac-planner-is-it-possible-to-make-the-robot-reverse-without-changing-heading/
navigation2 team has worked to bring `allow_reverse` parameter to RPP.
I was wanting to work with it but Galactic Debian is currently using Galactic Sync 2 from Navigation2 upstream whereas the changes to allow reversing in RPP were made for Galactic Sync 3. https://github.com/ros-planning/navigation2/pull/2443

Can you please give a tentative timeline for when we will have Galactic Sync 3 available in the Debian, especially the reversing feature.

**Required Info:**

- Operating System:
  -Ubuntu 20
- ROS2 Version:
  - Galactic
- Version or commit hash:
  - https://github.com/ros-planning/navigation2/pull/2443
- DDS implementation:
  - rmw_cyclonedds_cpp

#### Expected behavior
Robot was able to reverse i.e move backwards without changing its heading.

#### Actual behavior
Robot turned its heading and navigated towards the goal.

**Comment by SteveMacenski** [comment]
I plan to do a sync against the distributions sometime this month, I've just been slammed. I would tentatively plan on Sept 15-17 as a timeline I could get one done in. 

Thanks for the reminder, it has been quite awhile since I synced the distributions. I added it to my calendar to do it mid-week next week.
