### ISSUE TITLE
[map_server] map loading in raw mode issue

### ISSUE THREAD

**Issue by doisyg** [ros-planning/navigation2#2590]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 220.04
- ROS2 Version:
  - galactic last sync
- Version or commit hash:
  - galactic last sync
- DDS implementation:
  - Cyclone

#### Steps to reproduce issue
Load a png file with a wide range of values in RAW mode.
Pixels more than 39.2% full will be marked as unknown in the generated OccupencyGrid

#### Expected behavior
Preserve the full scale from 0 to 100% 

#### Additional information
I believe this is due to that part of map_io:
https://github.com/ros-planning/navigation2/blob/0513db1cf94481958d43ac4e3d15100f2c91c245/nav2_map_server/src/map_io.cpp#L237-L247

`occ_percent` is in the [0-255] range and `nav2_util::OCC_GRID_OCCUPIED` is equal to 100

If this diagnostics is shared, I think the fix will be to remove `&& occ_percent <= nav2_util::OCC_GRID_OCCUPIED`

----

**Comment by doisyg** [comment]
Ok, I got it now, example of conversion between occ_grid and costmap:
https://github.com/ros-planning/navigation2/blob/0513db1cf94481958d43ac4e3d15100f2c91c245/nav2_costmap_2d/src/costmap_2d.cpp#L84-L88

Hence I believe for the raw loading mode we should have:

```
map_cell =
   std::round(shade * (nav2_util::OCC_GRID_OCCUPIED - nav2_util::OCC_GRID_FREE));
```
In order to map the full image range to the full occupancy grid range

**Comment by SteveMacenski** [comment]
A "costmap" is different from an "occupancy grid" so they have different conventions. A occupancy grid is strictly 0-100 or containing free/occupied/unknown quantities. 

The costmap is an object using specifically what we can store in the char easily, which is 0-255 so we take advantage of the full bits we have available so we can create more smooth potential fields through inflation. If there was some fundamental type that only did 0-100, the folks at willow probably would have used that instead. But since we have 255 values, we should use 255 values. But this is also super specific to the implementation of a costmap in ROS, there's no fundamental special reason for 255 in theory. We could instead use an `unsigned int` and have 4,294,967,295 unique values (as an extreme example). There does it a point of unhelpfulness of too discrete of values. 

Regarding the specific changes, I believe my colleague @AlexeyMerzlyakov is best suited to be your contact point. He has more recent familiarity with this part of the codebase than myself. He's on vacation right now though, so it'll take about a week before he'll get back to you. I have a good understanding of occ grids / costmaps, but not really much in the image parsing libraries and terminology employed by the current map server implementation. 

 The int in utils is probably a mistake, that was added by Intel and is non-original to the stack from ROS 1

**Comment by AlexeyMerzlyakov** [comment]
BTW, it looks like the question about map and costmap formats raised not first time. I think, this diverse to be properly documented, something like partially described at https://navigation.ros.org/tutorials/docs/navigation2_with_keepout_filter.html, but fully explaining input `map.file` formats, OccGrid format utilizing in Nav2 and conversion between `map.file`->`OccupancyGrid`->`Costmap2D` formats. Say, one new page in "Configuration Guide" chapter.
