### ISSUE TITLE
Allow reversing feature in RPP fails due to negative value of a variable

### ISSUE THREAD

**Issue by Naraharirahul** [ros-planning/navigation2#2594]
Hi, With respect to my previous issue #2580 I have been trying to test the reversing feature in my simulation and I found a issue that it fails to reverse when a goal pose was given (behind the robot with same heading angle) but can move forward without any error.

While debugging the code of `regulated_pure_pursuit_controller.cpp` on the galactic branch, I saw that the `projection_time` variable at the time of calculation is getting divided by the linear_velocity which would be negative if the goal location was behind and `allow_reversing` is set as `true`.

https://github.com/ros-planning/navigation2/blob/ba9851280f747434f143762c6211d5eb8a34e9b3/nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp#L398

This made the variable `projection_time` a negative value and not only that it caused the `while loop` not to break at all.
The if condition should break the while loop but as the variable `i` is being incremented, the `max_time_to_collision` is a positive value (lets say 1.0) and the `projection_time` is a negative value, it is not entering the if condition.

https://github.com/ros-planning/navigation2/blob/ba9851280f747434f143762c6211d5eb8a34e9b3/nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp#L406-L430

I solved the issue by adding `std::abs()` to the `linear_vel` in the following line and after that it has started to reverse. 
Let me know if this is the right way of resolving this issue and if not, what should be the best way of dealing this?

https://github.com/ros-planning/navigation2/blob/ba9851280f747434f143762c6211d5eb8a34e9b3/nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp#L398

**Comment by SteveMacenski** [comment]
> I have been trying to test the reversing feature in my simulation and I found a issue that it fails to reverse when a goal pose was given (behind the robot with same heading angle) but can move forward without any error.

I'm not sure how much more clear I can be than the explanation given in your last ticket. The changing in direction is caused by cusps in the path requiring a change in direction. Simply because your goal is behind you does not mean the robot will reverse to achieve it. The path planned has to indicate to the controller that a change in direction is necessary. That is done via a cusp which is the most clear and fundamental description of a hard change in continuity.

**Comment by padhupradheep** [comment]
> There's an argument to be made for the initial conditions on the path being reverse instead of forward though. Whereas a path isn't starting forward, but starting reverse, so there isn't a cusp for changing the direction, we're simply starting in the reverse direction. We assume all paths are starting forward. I'm not sure off the top of my head how to accomplish that though, but that's a valid point. I'd be open to a proposal!

This is a valid point, which I was thinking for soo long. One quick solution that comes to my mind is to utilize or split `use_rotate_to_heading` parameter. Currently when this parameter is set to True, it basically does three functionalities, that includes:
- `RotateToPath`
- `RotateToGoalHeading`
- `RotateToHeading`

If we are planning to reach the goal by starting in reverse direction, we need to set `RotateToPath` and  `RotateToHeading` - False. Following, we need to then simply make the robot follow the carrot and follow the existing solution that we have for handling the cusps and so on. 

But, again `starting_in_reverse` needs to be a parameter, since it is not safe for all the robots. 

Thoughts?
