### ISSUE TITLE
RPP approach velocity scaling should not use lookahead distance as a metric

### ISSUE THREAD

**Issue by Aposhian** [ros-planning/navigation2#3045]
#### Feature description
Currently, RPP decides when to trigger approach velocity scaling based on if the actual lookahead distance is different from the requested lookahead distance by a certain margin. This is problematic because lookahead distance is determined from current velocity, so there is a cyclic dependency that can lead to oscillations at the stop point.

```mermaid
graph TD
    velocity --> lookahead_distance --> velocity_scaling --> cmd_vel --> velocity
```
![image (6)](https://user-images.githubusercontent.com/16969110/175988043-4ee8e0bc-fe1d-47e2-bfd7-7e28bc391de0.png)

#### Implementation considerations
Rather than looking to lookahead distance as a proxy measure, I wonder if there is some way to pipe the distance to the goal from a goal checker? Because simple euclidean distance to the goal pose may not be compatible with all goal checkers.

Velocity smoothing and motion profiling has been suggested as a fix to this issue, but I think that we should be able to come up with a simple solution for RPP that fixes this underlying cyclic dependency in the algorithm.

**Comment by SteveMacenski** [comment]
From https://github.com/ros-planning/navigation2/issues/2971

> The first place I'd go is to say that the distance error is the wrong metric to use because of this case. Instead, we could have it be a radius to goal metric with the same other logic. If the last point on the path is within lookahead_dist radius, apply the same logic with the same 'error' calculation. That would be a similar proxy, though inexact.

Perhaps that is the answer? Just a new parameter for proximity to apply it and have the velocity scaling be a function of radial distance from goal rather than lookahead error? I believe this would also solve your other ticket https://github.com/ros-planning/navigation2/issues/2971

> I wonder if there is some way to pipe the distance to the goal from a goal checker? 

The thing about the goal checker is that is to check if its within tolerances to stop navigation entirely. We would need to be scaling velocities to slow down before we got into that tolerance range from what a goal checker would have to say - else we (1) just stop abruptly negating the feature or (2) overshoot the goal because we only then start to slow down.

**Comment by SteveMacenski** [comment]
> What if it looked at the integrated path distance remaining on the transformed plan as the criteria for when to apply approach velocity scaling? That would make it not have to indirectly reference lookahead distance like the current approach does.

Agreed, and solve the other ticket too

**Comment by SteveMacenski** [comment]
Merging imminent
