### ISSUE TITLE
costmap_2d_node: enable setting namespace from launch files

### ISSUE THREAD

**Issue by tonynajjar** [ros-planning/navigation2#3213]
#### Feature description

I want to run a standalone costmap node and set its (parent) namespace from the launch file because it is dynamically generated.
Currently this is not possible as stated in this [comment](https://github.com/ros-planning/navigation2/blob/main/nav2_costmap_2d/src/costmap_2d_ros.cpp#L70) 

This is a feature request to enable this all while retaining the current functionality of setting the namespace via NodeOptions

If you agree, I can contribute here with some guidance what you'd like the design to look like

**Comment by SteveMacenski** [comment]
Seems sensible. You may be able to find the namespaces / remaps in the `main.cpp` file that you can just populate into the constructor so that it uses that code to perform what you want. Its a round-a-bout way of getting the same behavior, but is the lowest technical effort I believe. Though, if you can find another way to messing with node options that doesn't break current behavior, have at it!
