### ISSUE TITLE
Should 'smart_planner' be changed back to 'global_planner'?

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#325]
We took dijkstra from NavFn and called it dijkstra_planner, then @SteveMacenski added the Astar algorithm into it and named it smart_planner. It seems to me its now equivalent in function to the ROS1 NavFn global_planner again so maybe for compatibility and to reduce confusion we should rename it to global_planner?

Thoughts?

**Comment by SteveMacenski** [comment]
`global_planner` and `navfn` are completely different projects. The method and code (as far as I know) between them is totally different. We used `navfn`s A* implementation in the `smart_planner` which has no relation to the `global_planner` code. If we renamed it that way, that would be very deceptive as its not the same.

Moreover, my intention was to add a few more planners in there like RRT* and such but that's on a shelf for the moment.

**Comment by SteveMacenski** [comment]
David Lu also brought up in his ROSCon talk that `global_planner` was more or less a failed project - so I wouldn't want to rename to align with that. We're not having plugins for potential fields and tracing methods - its just a hardened implementation from `NavFn`

**Comment by mkhansen-intel** [comment]
Thanks for the history, I don't know all of it myself. I was just thinking of it in terms of what it does, it creates a path. Maybe it should be path_planner? smart planner seems non-descriptive to me, and implies other planners are stupid? how about path_planner or 2d_path_planner? I'm just trying to make it self-descriptive.

**Comment by SteveMacenski** [comment]
I picked the name because it sounded cool :1st_place_medal: but particually it was my hope to have that server actually accommodate a number of other planners like smoothed RRT-variants and maybe something ML-based. We could make it smart by switching to another planner if it fails to plan in the default mode.

path_planner and such are so vague, giving it a pointless name like `smart` is of similar help. If we called it `nav2_navfn_planner` that would be the most correct

**Comment by mkhansen-intel** [comment]
Adding @orduno to the discussion, since he ported this originally and should give input. 

Here's my suggestion, we go back to `nav2_navfn_planner` like you suggested for this node, and for your suggestion of adding more types of planners, I think those should be additional new packages & server nodes. You could call navfn, if that failed, you could call another planner instead. I don't know that we want to have one planner implement every algorithm, do we?

**Comment by mikeferguson** [comment]
Honestly, after watching the development on ROS1 navigation, I'd suggest that each planner should be it's own package -- any commonality should be in a planner_utils package or similar -- otherwise the code bases tend to quickly become a pile of unmaintainable mush.

(In ROS1 we had both trajectory rollout and DWA in the base_local_planner, and they are similar, but just different enough, that the codebase was quite hacky. In the case of something like RRT, I imagine the code is highly different from navfn, and they probably wouldn't share much code anyways).

**Comment by mkhansen-intel** [comment]
Thanks for the comment Mike, that's along the lines of my thinking also. I don't know that we'll be able to do that in time for Crystal in this case, I'm not sure how long it will take for that refactor. Assuming we can't do that in time, do you have a strong opinion about the name of the planner in the first release?

**Comment by SteveMacenski** [comment]
With all that in mind, I think `nav2_navfn_planner` is the move since that library contains  the A* and dijkstras implementations. I dont think its worth splitting those 2 out into 2 planners as they share 99% of the same functional code, but I could buy into something higher level of planner switching

**Comment by mikeferguson** [comment]
I concur that nav2_navfn_planner seems appropriate

**Comment by orduno** [comment]
I think it's a good idea to rename the `nav2_smart_planner`. How about `nav2_planner`? Currently, this class serves as a Task/Action server wrapper and hosts a single planner implementation `navfn`.

I have plans to extend this significantly and have it manage different kinds of planners. As described on #225, we'd like to achieve sufficient generalization for various families of planners and check that the world model supplies the required world representation.

This class, eventually, will manage multiple planners, compute plans using very different approaches, rate them and select the best for execution.

**Comment by orduno** [comment]
I think we can close this issue and continue the conversation on issue #225.
