### ISSUE TITLE
[smac_planner]Some question about node_hybrid.cpp's implementation

### ISSUE THREAD

**Issue by StetroF** [ros-planning/navigation2#3465]
## Bug report

**Required Info:**

- Operating System:
  - 
- ROS2 Version:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 

#### Steps to reproduce issue

in this file's function named getObstacleHeuristic()
i've read the source code,I thought that the way to get ObstacleHeuristic from start_point to goal_point is DijkStar algorithm.
Then in this function
```
  std::make_heap(
    obstacle_heuristic_queue.begin(), obstacle_heuristic_queue.end(),
    ObstacleHeuristicComparator{});
```
 i test this function by provide 10 random nuber which are 83 86 77 15 93 35 86 92 49 21 in the same struch with obstacle_heuristic_queue,then i use this make_heap function,I got the result  which were 15 21 35 49 83 77 86 92 86 93,
 and i use pop_heak ,pop_back and iterate thses 3 function for 10 times ,every time i got the minium number in the first place in heap,
 so i think that before expand , i will get the point which is closet to start_point.
 And then,Use Dijkstar Algorithm expand the "obstacle_heuristic_lookup_table" value and update "obstacle_heuristic_queue" value,
 expand next point with the closet point whose "obstacle_heuristic_lookup_table" didn't update(I thought the value are all be 0 before update by "resetObstacleHeuristic"function),so i think the expansion shoud stop when the goal_point's obstacle_heuristic_lookup_table value is update,should
```
     if (idx == start_index) {
      break;
    }
```
 be included in while? And should this judgement condition change from start_index to goal_index?So that this function can judge whether the value should continue update or not.Othervise,even though you update the goal_point's obstacle_heuristic_lookup_table value, the function won't stop update other point's value

#### Additional information

----

**Comment by SteveMacenski** [comment]
We search in reverse from goal -> start so that we can cache the values of the heuristic for replanning for the same goal in a new starting position as the robot makes progress towards the goal, `start_index` is correct since that is the terminal condition. Because we're using Dikjstra's the first time we hit the goal condition is guaranteed to be the optimal solution so we don't need to continue to expand as we'd need to in A* for finding the optimal solution. Everything is updated by the time that `break` happens since its at the bottom of the for loop.
