### ISSUE TITLE
nav2-smac-planner package not available on foxy

### ISSUE THREAD

**Issue by guidout** [ros-planning/navigation2#3549]
Sorry if this might not be the right spot for this question.

I'm trying to install the smac-planner package on Foxy but apt install can't find it. Is it not available?

Thank you in advance

**Comment by SteveMacenski** [comment]
Its called just the Smac Planner in Foxy https://github.com/ros-planning/navigation2/tree/foxy-devel/smac_planner mostly due to me messing it up. I couldn't change the name back after release so we just have to live with it like that in Foxy unfortunately. I would definitely recommend upgrading to at least Galactic though if you're using the Smac Planner. There are many updates made that were not backported to Foxy.

**Comment by guidout** [comment]
thank you for replying and also for the awesome work you do and share.

**Comment by SteveMacenski** [comment]
Yeah

**Comment by WinstonHChou** [comment]
Just a quick question, is it possible to build newest smac-planner from source in foxy?
Is there any structure of ros2 that is not supported by ros2 foxy?

**Comment by tonynajjar** [comment]
> Is there any structure of ros2 that is not supported by ros2 foxy?

Hard to say but easy to try :slightly_smiling_face:.
