### ISSUE TITLE
costmap clearing 

### ISSUE THREAD

**Issue by osama-z-salah** [ros-planning/navigation2#3753]
My current setup involves a single LiDAR sensor that covers only a limited 220-degree arc of the robot's surroundings. As the robot moves, any obstacles seen by the LiDAR previously and not in the LiDAR coverage remain on the costmap since the costmap can not raytraces them, as there are no laser beams that can be traced in that region. This creates a challenge as the costmap, responsible for guiding the robot's path planning, cannot effectively update and clear regions where the LiDAR doesn't provide data. Consequently, the costmap becomes cluttered with numerous false obstacles, significantly affecting the map's accuracy and usability.

What would be the best technique to tackle this?

**Comment by SteveMacenski** [comment]
Please ask on Robotics Stack Exchange (new ROS Answers starting today). 

In general, questions about your application don't belong in the issue tracker. Please use the Q&A-style resources available in the community moving forward (and/or googling your own questions and seeing how other people deal with it). Otherwise, Open Navigation LLC does provide consulting services (info@opennav.org). 

Unfortunately time is limited and I can't respond individually to every problem each user might run into or explain the basics of how things work when there is a body of literature / videos / documents / etc in existence which go over the concepts.
