### ISSUE TITLE
Costmap_2d: how to support cost values as double datatype

### ISSUE THREAD

**Issue by xyaoab** [ros-planning/navigation2#3949]
Hi team, 

Is there any specific reason that `unsigned char` instead of `double` is supported in [cost values](https://github.com/ros-planning/navigation2/blob/main/nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d.hpp#L149) in nav2_costmap_2d
/costmap_2d.hpp?

#### Feature description

We are using distance to the nearest occupied cell to represent the cost value in the costmap. `double` is expected to have higher precision.

**Comment by SteveMacenski** [comment]
Because unsigned chars are the underlying data in the costmap, not doubles. Its 1/8 the size allowing it to scale better. I won't say that that'll always be the case, but it was a solid engineering decision back with the resources we had in the 2000s when Willow was working on that package. Its on my agenda in 2024 to enable more flexibility here, but today, unsigned chars are your options. 0-255.
