### ISSUE TITLE
Still facing problems with global planner.How can I fix generated global plan and stop replanning?

### ISSUE THREAD

**Issue by Rak-r** [ros-planning/navigation2#4037]
## Question

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- ROS2 Version:
  - Humble

I am working on an application with car-like robot, what I want is that the global planner (Smac Hybrid A*) to generate a plan from (say point A to B) for once but the don't update every time. How can I achieve this behaviour.

#### Additional information

I have opened a query and which also includes an issue I am facing with planning. 
https://robotics.stackexchange.com/questions/107449/still-facing-problems-with-global-planner-to-generate-plan-in-nav2

This might be to do with planner frequency params but I am bit unsure about it, so any insight/walkaround suggestion from experienced people would be helpful.
@SteveMacenski

**Comment by SteveMacenski** [comment]
Please don't cross past with stack exchange. If/when folks are able to help with your question there, they will :smile: 

Some tips to get more / better responses on stack exchange:
- Keep it to one problem at a time
- Describe your problem in detail and be clear, other people aren't likely to be running into the exact flavor of problem you're running into at a particular time to read between the lines
- Do some debugging first and let folks know what you've already found out

**Comment by Rak-r** [comment]
Thanks for the suggestion. @SteveMacenski 

However, that's what I have done from past issues and it didn't got solved even after giving details from my end.

That is why I ended up opening the issue here after waiting and debugging it myself. 

The issue in stack exchange highlights only one problem which was already asked previously but not able to solve that from my end.

The other part just ask a question which I added in this issue as well which got closed now.

**Comment by SteveMacenski** [comment]
Not every problem is something that is going to receive 'here's the precise answer' answers. We're an open-source community and only have so much time to answer user questions -- and this particular query sounds more in depth of user configurations and application details than the maintainers can ask / respond to 20 Q&As to get to the bottom of what you're trying to do and where its going wrong, which sounds like multiple places. What you're trying to do is definitely possible, but it will require you to read the documentation and understand the techniques you're trying to apply. 

I'm definitely not trying to funnel open-source questions into Open Navigation's consulting business in general, but the detail and level of engagement to fully understand and resolve your issue sounds like it might fall into that category if you're unable to find root cause and resolve it yourself (which I think you should be able to). If that's something you'd be interested in, email info@opennav.org. Unfortunately I can't dedicate 10 hours of my time to trying to resolve every user's individual configuration quirks (else I'd never get anything done)

**Comment by Rak-r** [comment]
I understand your suggestions and thanks for your time. 
I am just trying to setup simple NAV2 stack for Ackermann-steered robot for which I know this is something related to configuration issues. I have gone through the documentation and trying to dig it deeper but some what coming to this end it seems to be bit confusing which parameter to change in global and local costmap params. 

I have turned on clearing = true
under costmap params, the issue seems to me that it is considering the starting cell as occupied.
