### ISSUE TITLE
Feature Request: Enhanced Filter with Rescue Mode for Accidental Entries into 'Keep Out' Zones

### ISSUE THREAD

**Issue by BCKSELFDRIVEWORLD** [ros-planning/navigation2#4085]
**Required Info:**
- Operating System:
  - Ubuntu 22.04
- ROS2 Version:
  - Humble
- Path Planner:
   - Smac 2D Planner
 - 2D Localization:
   - Cartographer

#### Current Situation:

-The 'keepout' filter effectively prevents the robot from entering certain areas, influencing the path planner. However, minor localization discrepancies can sometimes lead to accidental entries into 'keep out' zones. This issue is particularly prevalent in variable environments.
-The 'speed filter' slows down the robot upon entering specific areas, but it does not influence the global planner as it does not create additional cost around these areas.

#### Proposed Solution:
I propose a new filter that will function as a rescue mode during accidental entries into 'keep out' zones. This filter will gradually slow down the robot and provide time to correct localization discrepancies. Specifically, this new filter will:

 - Gradually slow down the robot when it accidentally enters a 'keep out' zone, allowing the localization system to adjust and safely guide the robot out of these areas.
 - Enhance the robot's perceived safety and navigation efficiency during these incidents. This will enable the robot to operate more safely and effectively.

#### Implementation considerations
This improved filter will enhance both the safety and navigation capability of the robot, especially in complex or variable environments, by mitigating risks associated with unintended entries into restricted areas.

**Comment by SteveMacenski** [comment]
Nice feature request! The keepout / other filters all have disable/enable parameters or services that can be dynamically turned off and on. While that is a pretty good first order solution, if you have to disable it to get out, then it can navigate freely within that keepout zone until it leaves.

I don't think your suggested solution is a great fix though. Slowing the robot if its in a keepout zone doesn't seem like it'll help much. Something better to do would be to check the robot's pose and do something based on that. For instance, if the robot is detected to be within a keepout zone, change the keepout cost from LETHAL to `252` (1 below inscribed) to make it _very_ high cost so that the robot tries to navigate out of it. Once the robot's pose is detected to be out of the zone, it resumes being set to lethal. 

Another way of handling this that's a bigger development effort would be to change the get cost API to consider the previous pose and the current pose of the robot. In that case, we set it to lethal if the previous step is non-keepout and the current is keepout. But once current is keepout, the next would be `252`. I don't have a fully baked idea there yet though, but I think more something to consider in thelong-term
