### ISSUE TITLE
[Discussion] Can MPPI follow the global path that has multiple segments, each represents forward or reversing movement.

### ISSUE THREAD

**Issue by Chortine** [ros-planning/navigation2#4195]
Hi Team,

I have a global path planner that outputs a global path, which is divided into multple segments, and between each segement, the car alternating its moving direction: either moving forward or moving reverse. My car model is ackermann car, and the reverse moving segment is not trival for the car to arrive at the target pose.

Given this context, my question is, can the current implementation of MPPI controller follow a global path like this? If not, what will be the best way to modify it to achieve this?

Thank you very much.

**Comment by SteveMacenski** [comment]
That is sufficiently vague that it’s hard for me to say anything about anything with confidence 🙃

But yes, MPPI is being used and has been shown in Guillaume’s ROSCon 2023 talk on bidirectionality in Nav2 to be able to change direction with reversing segments of paths from the Smac Planner. The important path attribute is that you set the orientation vectors in the path so that it’s decipherable that you want an explicit change in orientation for direction of travel. 

MPPI’s critics then have settings where it’ll pick up on those and use them in their behavior scoring. I’d highly recommend @doisyg ’s talk: https://vimeo.com/879000809/b32f8ebec4

**Comment by Chortine** [comment]
Hi that's exactly what I want! Here is what my global path looks like:
![ztLKo9QFGr](https://github.com/ros-planning/navigation2/assets/107395103/b9edd66d-01b7-4b95-89c2-df09013d8eea)

I set orientation in path and set `PathAlignCritic.use_path_orientations = true`, and it works!
Especially, the built-in removePosesAfterFirstInversion() function is very useful!

**Comment by SteveMacenski** [comment]
Great! Sounds like its solved?
