### ISSUE TITLE
DWB fails when goal is directly opposite of robot along X or Y axis

### ISSUE THREAD

**Issue by mhpanah** [ros-planning/navigation2#451]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source
- Version or commit hash:
  - master
- DDS implementation:
  - default
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

When robot is located near the center of a pole and the the 2D Nav goal is on the other side of the map near the center of the pole, the local planner fails with the following error msg:
```
[ERROR] [DWBLocalPlanner]: No valid trajectories out of 399! 
[ERROR] [DWBLocalPlanner]: 1.00:   GoalDist/Trajectory Hits Unreachable Area.

```

#### Additional information
![screenshot from 2018-12-07 17-03-16](https://user-images.githubusercontent.com/39755151/49679762-a3576780-fa42-11e8-9a5b-b767b15a4a94.png)

**Comment by mhpanah** [comment]
@SteveMacenski The re-planning is pushed to the master, but currently we are launching the SimpleNavigator from the launch file.

**Comment by bpwilcox** [comment]
This looks like this could be the same issue I noted  in #456 when running the full stack with the obstacle layer observations enabled

**Comment by crdelsey** [comment]
The problem seems to lie with map grid class, in the way it expands nodes in its distance matrix. The resulting matrix looks like this:
![image](https://user-images.githubusercontent.com/39749483/50619401-ec69d280-0ead-11e9-9127-c06f3c810ae2.png)

If I force the `MapGridQueue::validCellToQueue` function to always return true, navigation is successful.
