### ISSUE TITLE
Update BTs with recovery

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#482]
Instead of having a separate BT node to stop the robot motion (`nav2_tasks::StopAction`), we could define a tree node to dynamically halt a sub-tree. [See details here.](https://github.com/BehaviorTree/BehaviorTree.CPP/issues/36)

**Comment by orduno** [comment]
Bellow is our current behavior tree with simple navigation and recovery and @facontidavide 's proposal

current | proposal
--- | ---
![](https://user-images.githubusercontent.com/2822888/49861157-85e81c00-fdfb-11e8-9bd6-e2635264b54e.png) | ![](https://user-images.githubusercontent.com/2822888/49861172-8f718400-fdfb-11e8-964a-69fa34dd9593.png)

So far I see two issues:
- We need two `IsStuck` nodes. While the first `IsStuck` node get's ticked periodically, the second doesn't. If these two nodes are independent, it's possible that one may detect that the robot is stuck while the other not. This could be potentially fixed by shared the state throught the BT::Blackboard.
- As shown, the navigation doesn't resume once the `stuck_recovery` BT subtree is executed.

**Comment by facontidavide** [comment]
Good points. 

I am not particularly worry about the first one, since there are multiple way to avoid issues there.

Focusing on the second one...

I have few ideas about how this can be solved. For example adding a __RetryUntilSuccesfull__ decorator to resume the entire tree after a recovery.

But this trigger a more profound question. what do you really want to happen?

- Do you want `BackUp` and/or `Spin` to be interrupted if  `IsStuck` becomes suddently true or do you want them to complete their routine?

- How many time do you want to resume `navigation_subtree` after a `stuck_recovery`? A limited amount of times? 

The more details you give me about the desired behavior, more I can help ;)

Cheers

**Comment by orduno** [comment]
Closing the issue as we have a new behavior tree for robot recovery `navigate_w_replanning_and_recovery` that fixes this.

FYI, the logic on the new bt tree is different, we no longer check for preconditions and only do recovery if planning or control fails.
