### ISSUE TITLE
Make A* the default global planner

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#528]
#### Feature description
A* is the most commonly used global planner for navigation tasks. It should be the default used by the navigation 2 stack

#### Implementation considerations
This should just be a matter of changing default parameters in the global planner. However, testing is needed to ensure it is reliable, and that better performance is achieved.

**Comment by EwingKang** [comment]
I've tried to set the A* as the default global planner in the launch.py, however, the trajectory seems to be quite rugged compare to the relatively smooth planning of the default (dijkstra?). Sometimes it would even show some weird triangle along a straight path, that is clearly not the best path. 
Not sure if this is a bug or I misjudge the performance of A*. Unfortunately I don't have any screenshots. Will post some when I'm available.

**Comment by mkhansen-intel** [comment]
@orduno - have you tried the A* algorithm and have you seen this?

**Comment by crdelsey** [comment]
I tried the A* planner and during my tests, the resultant path seemed acceptable. It might have had a bit of extra wobble to it. I'll have to do more testing.

I also ran 100 iterations of the system test and it passed as well as dijkstra.

Given that, I figured I'd go ahead and enable it by default on master. That way we get more eyes on it. PR #571.

I'll continue testing in the meantime.

**Comment by SteveMacenski** [comment]
phew, I did that refactor and worried I messed something up.

As a side note: the navfn planner in ROS1 *never* actually had the A* implementation of navfn exposed. For A* we all generally used the `global_planner` which by itself has a number of problems that David could better explain than me. 

If you see issues in A* in navfn, you might not be crazy, it might just have issues that we can work out. If we determine its an issue with the implementation, I'm more than willing to produce another implementation. Motion planning is my jam

**Comment by mkhansen-intel** [comment]
Good job @crdelsey, and thanks @SteveMacenski for the offer to help resolve issues with A*

**Comment by crdelsey** [comment]
> For A* we all generally used the global_planner

Sounds like we need to do some comparisons between navfn in A* mode and the ROS1 `global_planner` to ensure we are achieving comparable performance then.

**Comment by SteveMacenski** [comment]
Perhaps, you'd have to ping @DLu on how similar they are since `global_planner` was greatly his work. He might have some insights on it

**Comment by DLu** [comment]
[Main Source](https://github.com/locusrobotics/robot_navigation/tree/master/dlux_plugins)

There's two main parts of the global planning algorithm. A*/Dijkstra are options for what I call the Potential Calculation, and then there's different options for the traceback. 

![global planner diagram](https://raw.githubusercontent.com/locusrobotics/robot_navigation/master/dlux_plugins/doc/10-Dij.png)

In the above diagram, the blue path traces back a path using each cell's four neighbors. The red path uses the eight neighbors, and the green uses a fancy gradient descent algorithm (which is what navfn did by default)

If you use Dijkstra (as in the above diagram), you expand a lot of "extra" potential, but that means there's lots of numbers to calculate the gradient off of. 

Depending on which heuristic you use with A*, you can get a variety of different (technically valid) paths that may seem "rugged" because there isn't as much potential to calculate a gradient with. Example: 
![rugged good looking path](https://raw.githubusercontent.com/locusrobotics/robot_navigation/master/dlux_plugins/doc/11-AMan.png)

I don't have hard numbers to back up these assertions at the moment, but in general my experience has been
 * When doing planning on "typical" size maps, Dijkstra is often faster than A*, given that maintaining a priority queue in A* can be quite costly. 
 * There is a complicated optimized version of Dijkstra in navfn that I never fully understood. When I ported it to `dlux`, the result was slower than my straight forward implementation of Dijkstra, but its entirely possible that the subtleties of that optimization were lost on me / in my translation. 
 * It's possible that the A* in navfn was more efficient than my implementation, but I never tested it.

**Comment by crdelsey** [comment]
@DLu Thanks for the background. The explanation for the ruggedness of the path using A* likely explains what I was seeing.

**Comment by EwingKang** [comment]
Those orange spikes in the second picture exactly resembles what I'm seeing in the A*!  Thank @DLu for the explanation.

**Comment by orduno** [comment]
Sounds like the best option, for now, is to keep Dijkstra as default. We would need to test with "large" size maps to evaluate performance.

We should also try the `dlux_planner` with nav2! @DLu is it in your plans to port `dlux` to ROS2?

**Comment by crdelsey** [comment]
Blocked until we have a good way of evaluating the results

**Comment by DLu** [comment]
Not that there's anything to report, but the issue will be tracked here: https://github.com/locusrobotics/robot_navigation/issues/45

**Comment by crdelsey** [comment]
Closing since this isn't addressing a specific need. We can reinvestigate when performance testing shows an actual problem

**Comment by SteveMacenski** [comment]
@crdelsey well more than anything else, has anyone set the use A* parameter and shown that it actually _works_ ?

**Comment by crdelsey** [comment]
In the system test, test_bt_navigator has it turned on while test_bt_navigator_dijkstra has it turned off

**Comment by SteveMacenski** [comment]
Awesome

**Comment by jihyunl2** [comment]
@orduno Are there any updates on "large" map performance with Navfn Dijkstra planner? We are using this as our default planner, and with a 1772x1077 px map, we're having trouble getting even 5Hz frequency with ComputePathThroughPoses. We want to check whether it's a computing power issue or something else isn't right.
