### ISSUE TITLE
Check for collision before executing the spin primitive

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#533]
The spin primitive from `nav2_motion_primitives` should check, based on the robot footprint, if the path is clear before execution.

**Comment by orduno** [comment]
@bpwilcox since you are working on the collision checker, I'll reassign it to you and move it to "in-progress".

**Comment by SteveMacenski** [comment]
@bpwilcox I started to look at this. How Navigation did it was through the [costmap model](https://github.com/ros-planning/navigation/blob/melodic-devel/base_local_planner/src/costmap_model.cpp) which requires access to the costmap object. This wasnt a problem with the plugin infrastructure since it was in the same node. I'm curious if you're planning on retooling it to work with the occupancy grid message.

Let me know if I can help in some way.

**Comment by bpwilcox** [comment]
@SteveMacenski I am soon to submit a PR to address this. Yes, I am using the same costmap model, so I am subscribing to the costmap topic (actually I am now publishing a nav2_msgs Costmap msg) and creating the costmap object for use in collision checking.

**Comment by crdelsey** [comment]
Done now
