### ISSUE TITLE
Slow robot if DWB missing performance requirements

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#555]
#### Feature description
DWB fails to meet the desired performance when running an un-optimized build resulting in instability in the control loop. It would be desirable for DWB to dynamically reduce commanded robot speeds to the point where it can be controlled stably to make it possible to run debug builds or, alternatively on machines with insufficient performance.

This should be configurable so that DWB can instead fail or ignore the problem at the desire of the user.

**Comment by SteveMacenski** [comment]
My suggestion is to rather print warnings if in capable to reach performance requirements. Inside of the controller server rather than the DWB plugin so that its general for any consumer code. 

This however, as I found, is already implemented from our `nav2_controller` implementation. When building a system, if you start seeing these warnings, there's something wrong and that should be addressed in development. 

I'm going to close this ticket since if you're running your system so hot that this is happening, its a safety issue larger than just trying to throttle the controller rate. Throttling the controller rate on model predictive controllers (which TEB tangentially falls into) can actually be a critical failure resulting in collisions. 

Rather than designing a safety mechanism specific to DWB, I'd rather leave it how it is.

Closing. If you disagree, we can reopen to continue discussing.
