### ISSUE TITLE
Scrub parameter declaration in plugins

### ISSUE THREAD

**Issue by mjeronimo** [ros-planning/navigation2#714]
#### Feature description
Parameters can only be declared once per node. Normally, they are declared in the node's constructor. However, in the case of plug-in modules which are not themselves nodes, but use the parent node handle, the plugin's parameters are declared against the parent's node. Therefore, if a plugin is reset, uninitialized and reset, it should probably undeclare its parameters and redeclare them upon reinitialization. 

These are the modules we need to fix and where the parameters are declared:

- [x] Costmap2D plugins: onInitialize(), which is called by reset(). #752
- [ ] Dwb plugins: on initialize().
- [ ] Dwb local planner: loadCritics().
- [ ] Dwb core publisher: constructor. Might not be an issue
- [ ] Dwb critics: onInit()

**Comment by bpwilcox** [comment]
The ClearCostmap recovery behavior should be removed from behavior tree until this issue is resolved, otherwise there will be runtime errors when resetting the layer (at least static layer).

**Comment by SteveMacenski** [comment]
Plugins in costmap_2d have been often reset as a recovery. Would reinitializing the variables on reset incur any significant delay in operations since this is a pretty regular occurrence?

**Comment by orduno** [comment]
@SteveMacenski It's possible, we would have to test it. Perhaps there's no need to un-declare the parameters upon reset. Could you review #752? That should fix, at least temporarily, the bug.

**Comment by bpwilcox** [comment]
Since PR #1099, parameter re-declarations are being handled in most cases by using the added `declare_if_not_declared` utility function. The alternative seemingly suggested in this issue is to undeclare the parameters when the plugins are destroyed, as opposed to leaving them on the node. 

Are there any strong reasons we should move to specifically undeclare all parameters of a plugin (or any object declaring parameters during the `on_configure` call)? If there aren't any strong cases, I think the current solution resolves this ticket. @orduno

**Comment by SteveMacenski** [comment]
I'm happy with that. I think undeclaring is a bit excessive but if someone's a completeist I would understand.

Functionally, I dont know when I'm regularly loading and unloading plugins outside of restarting a process
