### ISSUE TITLE
colcon build error

### ISSUE THREAD

**Issue by routiful** [ros-planning/navigation2#739]
## Bug report

Failed to build navigation2

- Operating System:
  - Ubuntu 18.04, macos high sierra
- Installation type:
  - source
- Version or commit hash:
  - master(https://github.com/ros-planning/navigation2/commit/178c7c6ce4aa3ea58189302e1287d44f800543cd)
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
I attached references.
https://github.com/ROBOTIS-GIT/turtlebot3/issues/401#issuecomment-494182638
https://github.com/ROBOTIS-GIT/turtlebot3/issues/424#issue-443821707

#### Additional information
behaviortree_cpp should be installed to build navigation2 packages. 
But it always have made error messages when I initial build navigation2.
In my thought, it simply be fixed to modifiy CMakelists.

**Comment by crdelsey** [comment]
@routiful Sorry for the delay. I was on vacation last week.

There are a lot of different problems listed in those bug reports. None of the problems look like a failure to build the behavior tree library; they are all missing dependencies or incorrect use of the `install/setup.bash` files.

If there is a specific problem, let me know and I can try to fix it. However, to me the real problem is that it is too complicated to build everything from source for the average user.

I think the best solution is for us to keep the crystal-devel branch updated (at least until the Dashing release), and you can just ask your users to `apt install ros-crystal-navigation2` or, if you want to build from source to get the latest features, they can just run `rosdep install ...` before building.

**Comment by mkhansen-intel** [comment]
I think this PR https://github.com/ROBOTIS-GIT/turtlebot3/pull/432 submitted to the turtlebot3 repo points users to the crystal-devel branch of navigation2 and other packages. I haven't tested it myself but I think it would be good to do that and test it. That may resolve many user build issues. Once we have all the dashing updates done, we'll create a dashing-devel and you can update to using that or preferrably just install from binaries.

**Comment by crdelsey** [comment]
I believe build issues are fixed and stable if the user uses the ROS 2 dashing release and the navigation 2 dashing release. Closing this issue.
